<?php

class newsLetterWidget extends WP_Widget{
    public function __construct()
    {
        parent::__construct('test_news_letter', 'News Letter',
            array('description' => 'Une simple news Letter'));
    }

    public function widget($args, $instance)
    {
        echo 'news letter ta3na'; // TODO: Change the autogenerated stub
    }

}